---
title: "Construct Dataset"
output: html_document
date: "2025-12-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# Install baseballr through pacman - this may take ~30 mins
if (!requireNamespace('pacman', quietly = TRUE)){
  install.packages('pacman')
}
pacman::p_load_current_gh("billpetti/baseballr")
library(dplyr)
```

```{r}
game_pks <- mlb_game_pks("2025-06-06", level_ids = c(11))
dates <- seq(as.Date("2025-06-04"), as.Date("2025-07-04"), by = "day")

# Get all game codes of AAA from June 4th to July 4th
game_list <- lapply(dates, function(d) {
  game_pks_df <- mlb_game_pks(as.character(d), level_ids = c(11))
  game_pks_df$game_pk
})
# game_list is a list of lists - we unroll this
game_list <-  unlist(game_list)

# Get the list of filtered dataframes from every game
dfs <- lapply(seq_len(game_list), function(i) {
  game <- game_list[i]
  message(paste("Processing row:", i, "of", nrow(game_list), "| Game ID:", game))
  tryCatch({
  df <- mlb_pbp(game_pk = game)
  print(nrow(df)) # printing for verification purposes, this can be removed soon enough
  if (!"reviewDetails.reviewType" %in% names(df)) {
    df$reviewDetails.reviewType <- "NONE"
  }
  # I think MJ means a player-initiated review, although I'm not quite sure why
  # - J is pitch result, M is timed play(?)
  df %>%
    filter((details.hasReview == TRUE | # details and about catch two different
              # sets of plays which both seem to be challenges of balls/strikes
              about.hasReview == TRUE) &
             reviewDetails.reviewType != "NONE")
  }, error = function(e) {
  NULL
  })
})
# bind them together into the complete dataset of pitches with reviews
all_reviews <- bind_rows(dfs)

```


